[package]
name = "rustcpp"
version = "1.72.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.0"
bitfield = "0.14.0"
bitfield-struct = "0.5.4"